# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ad55e4a7d258f4728b763cb1d6bb6d9757adaa641c03f4851c08471f67304448c6e380e1ef2f6208550f9c25f5b44876888f56b4ecf221d8ab4d82e6bfe5254

test:
  secret_key_base: ef09011b0aba1882abce4e66d3ee3ec35aed9a1c8b38acc4fe304c2660b4151f2aa501006d61d3c5dbc7c8ebcb3c45836219366ff162fbfe52d6e00cb3d6ca5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
